language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=fileutils
  matrix:
    # Only use system (for speed) + latest version of OCaml.
    - OCAML_VERSION=system
    - OCAML_VERSION=4.08
os:
  - linux
  - osx
